### ISSUE TITLE
How do you access variables like DB_USERNAME from a container?

### ISSUE THREAD

**Issue by graingert** [maestrooo/eb-multi-container-skeleton#1]
@maestroo it looks like you setup some vars like DB_USERNAME and DB_PASSWORD, but I can't see where these are accessed

**Comment by bakura10** [comment]
You can accessed those using the getenv PHP method (example: getenv('DB_PASSWORD')).

**Comment by graingert** [comment]
@bakura10 these variables are available in all containers?

**Comment by bakura10** [comment]
I'm not sure, those are implemented as server variables so I suspect that yes, they will be available in nginx both. But I didn't try it :).

**Comment by graingert** [comment]
@bakura10 yes, they are published to all containers
